In [3]:
import numpy as np

In [6]:
## Accessing the array elements 

arr = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
arr[3]

4

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
## Multidimensional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [10]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [11]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [13]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [16]:
arr=np.arange(0,10,step=2)

In [17]:
arr

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [19]:
##copy() function and broadcasting

arr[3:]=100

In [20]:
arr

array([  0,   2,   4, 100, 100])

In [21]:
arr1=arr

In [22]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [23]:
arr

array([  0,   2,   4, 500, 500])

In [24]:
arr1=arr.copy()

In [25]:
print(arr)
arr1[3:]=100
print(arr1)

[  0   2   4 500 500]
[  0   2   4 100 100]


In [26]:
arr

array([  0,   2,   4, 500, 500])

In [27]:
### Some conditions very useful in exploratory Data Analysis

val = 2
arr<2

array([ True, False, False, False, False])

In [ ]:
##Create arrays and reshape

In [28]:
np.random.rand(3,3)

array([[0.14349027, 0.31718165, 0.05147775],
       [0.41516154, 0.19586255, 0.71038706],
       [0.6400549 , 0.34225107, 0.31443638]])