In [1]:
1+1

2

In [2]:
4*5

20

In [3]:
type(1)

int

In [5]:
type(True)


bool

In [6]:
True or False

True

In [7]:
lst_example=[]

In [8]:
type(lst_example)

list

In [9]:
lst=list()

In [10]:
type(lst)

list

In [11]:
lst=['Mathematics','chemistry']

In [12]:
len(lst)

2

In [13]:
type(lst)

list

In [14]:
lst.append("Krish")

In [15]:
lst

['Mathematics', 'chemistry', 'Krish']

In [16]:
lst[2]

'Krish'

In [17]:
lst[:]

['Mathematics', 'chemistry', 'Krish']

In [18]:
lst[1:]

['chemistry', 'Krish']

In [19]:
lst.insert(1,"Naik")

In [20]:
lst

['Mathematics', 'Naik', 'chemistry', 'Krish']

In [21]:
lst=[1,2,3,4,5,6]

In [22]:
lst.extend()

TypeError: list.extend() takes exactly one argument (0 given)

In [23]:
lst=[1,2,3,4,5]

In [24]:
sum(lst)

15

In [25]:
set_var=set()
print(set_var)
print(type(set_var))

set()
<class 'set'>


In [26]:
set_var={1,2,3,4,3}

In [27]:
set_var

{1, 2, 3, 4}

In [28]:
set_var={"Avengers","Ironman","Hitman"}
print(set_var)
type(set_var)

{'Avengers', 'Hitman', 'Ironman'}


set

In [29]:
set_var.add("Hulk")

In [30]:
print(set_var)

{'Avengers', 'Hulk', 'Hitman', 'Ironman'}


In [31]:
set1={"Avengers","Ironman","Hitman"}


In [32]:
print(set1)

{'Avengers', 'Hitman', 'Ironman'}


In [33]:
dic={}

In [34]:
type(dic)

dict

In [35]:
dic={1,2,3,4,5}

In [36]:
type(dic)

set

In [37]:
#Numpy(provides high performance multidimensional object and tools for working 
#with these arrays)


In [38]:
import numpy as np

In [39]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [40]:
type(arr)

numpy.ndarray

In [41]:
print(arr)

[1 2 3 4 5]


In [63]:
arr.shape

(3, 5)

In [64]:
my_lst1=[1,2,3,4,5]
my_lst2=[1,2,3,4,5]
my_lst3=[1,2,3,4,5]
arr= np.array([my_lst1,my_lst2,my_lst3])

In [60]:
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [61]:
arr.shape

(3, 5)

In [62]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [65]:
## check the shape of the array

arr.shape

(3, 5)